### ISSUE TITLE
Include arguments

### ISSUE THREAD

**Issue by Thanatermesis** [triantares/Elive-Web-widget#2]
Could be nice to use the tool with arguments, this will require some getopts code to parse the options, some suggestions:

* the default parameter should the URL to open
* --borderless
* --fullscreen
* --maximized
* --mute (no audio playing)
* --geometry (size of the window, in pixels, like 320x280)

other options from the webkit possibilities?

**Comment by triantares** [comment]
OK, but wouldn't "fullscreen" be beside the point for a gadget?
Unless one would want it as background, which I cann't imagine. :thinking: 

Most options you name there are Gtk options (not sure about "mute" though) and can be changed in the code directly.

**Comment by triantares** [comment]
Maybe keep this as a trunk widget for different projects and clone/fork each time something specific is needed like.
1. A web-widget (on demand like stock market) to run on-screen behind all the others i.e borderless, fixed size and fixed URL
2. Base widget for the installer using local .xml and/or html files.

**Comment by Thanatermesis** [comment]
I don't think it needs to be complex like using xml or forks, by just adding the CLI arguments, it allows to be used generically with any different possibilities for anything, this means: no need to fork it for different purposes, the main tool can satisfy all the needs

**Comment by TheTechRobo** [comment]
I think there's `sys.argv` for getting the parameters
